export const MAX_RETRIES = 3;
export const DELAY_MS = 500;
export const CONCURRENCY = 10;

export const ATTR_ALIASES: Record<string, string> = {
  started: 'startedOn',
  'started on': 'startedOn',
  completed: 'completedOn',
  'completed on': 'completedOn',
  age: 'age',
  height: 'height',
  'dominant hand': 'dominantHand',
  dominanthand: 'dominantHand',
  handedness: 'dominantHand',
  bifocals: 'bifocals',
  'visual issue': 'visualIssue',
  visualissue: 'visualIssue',
  'computer time': 'computerTime',
  computertime: 'computerTime',
  'dual monitor': 'dualMonitor',
  dualmonitor: 'dualMonitor',
  'dual monitors': 'dualMonitor',
  laptop: 'laptop',
  'sit to stand': 'sitToStand',
  sittostand: 'sitToStand',
  'sit to stand desk': 'sitToStand',
  demographic: 'demographic',
  demographics: 'demographic',
  discomfort: 'discomfort',
  discomforts: 'discomfortAreas',
  'discomfort areas': 'discomfortAreas',
  discomfortareas: 'discomfortAreas',
  'adjustment result': 'adjustmentResult',
  adjustmentresult: 'adjustmentResult',
  action: 'actionNeeded',
  actions: 'actionNeeded',
  'action needed': 'actionNeeded',
  actionneeded: 'actionNeeded',
  equipment: 'equipmentNeeded',
  'equipment needed': 'equipmentNeeded',
  equipmentneeded: 'equipmentNeeded',
  result: 'result',
  issues: 'adjustmentResult',
};

export const BODY_PART_ALIASES: Record<string, string> = {
  'upper-back': 'upperBack',
  'mid-back': 'midBack',
  'lower-back': 'lowerBack',
  buttocks: 'buttocks',
  head: 'head',
  neck: 'neck',
  eyes: 'eyes',
  'left-shoulder': 'leftShoulder',
  'right-shoulder': 'rightShoulder',
  'left-upper-arm': 'leftUpperArm',
  'right-upper-arm': 'rightUpperArm',
  'left-elbow': 'leftElbow',
  'right-elbow': 'rightElbow',
  'left-lower-arm': 'leftLowerArm',
  'right-lower-arm': 'rightLowerArm',
  'left-wrist': 'leftWrist',
  'right-wrist': 'rightWrist',
  'left-hand': 'leftHand',
  'right-hand': 'rightHand',
  'left-thigh': 'leftThigh',
  'right-thigh': 'rightThigh',
  'left-knee': 'leftKnee',
  'right-knee': 'rightKnee',
  'left-lower-leg': 'leftLowerLeg',
  'right-lower-leg': 'rightLowerLeg',
  'left-foot-or-ankle': 'leftFootOrAnkle',
  'right-foot-or-ankle': 'rightFootOrAnkle',
};